[package]
authors = ["lle-bout"]
edition = "2018"
name = "web-client"
version = "0.1.0"

[dependencies]
failure = "0.1"
serde = "1"
serde_derive = "1"
serde_json = "1"
stdweb = "0.4"
yew = "0.8"
chrono = { version = "0.4", features = [ "serde" ] }