FROM debian:stable-slim

SHELL ["/bin/bash", "-c"] 

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential ca-certificates curl \
&& curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh \
&& chmod +x rustup.sh \
&& ./rustup.sh -y \
&& rm rustup.sh \
&& source $HOME/.cargo/env \
&& cargo install cargo-web \
&& rustup target add wasm32-unknown-unknown